---
active_modules: [pygments_simple, tags, blog, wrap, typogrify]
author: Eric A. Meyer
canonical_url: http://susy.oddbird.com/
output_folder: ../output
template_path: ../templates
modules:
  pygments:
    style: borland
  blog:
    index_url: /blog/

# Banner
banner_title: Susy
banner_url: 'http://susy.oddbird.net/'
banner_tagline: 'your layout | <em>our math</em>'

# Navigation
nav:
  - name: Documentation
    url: 'http://susydocs.oddbird.net/'
    icon: list
  - name: Support
    url: 'http://stackoverflow.com/questions/tagged/susy-compass'
    icon: stackoverflow
  - name: Source
    url: 'http://github.com/ericam/susy/'
    icon: github
  - name: Twitter
    url: 'http://twitter.com/sasssusy/'
    icon: twitter
